//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerClub.DataAccess.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassSchedule()
        {
            this.ReviewClassSchedule = new HashSet<ReviewClassSchedule>();
        }
    
        public int Id { get; set; }
        public int IdBranchOficce { get; set; }
        public int IdWorkout { get; set; }
        public Nullable<int> DayWeek { get; set; }
        public Nullable<System.TimeSpan> StarTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> IdTrainer { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUdated { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual BranchOffice BranchOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewClassSchedule> ReviewClassSchedule { get; set; }
        public virtual Workout Workout { get; set; }
    }
}
