//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerClub.DataAccess.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewClassSchedule
    {
        public int Id { get; set; }
        public int IdClassSchedule { get; set; }
        public string Observation { get; set; }
        public int IdStaff { get; set; }
        public Nullable<bool> IsTrainer { get; set; }
        public Nullable<int> IdTrainer { get; set; }
        public Nullable<int> Members { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual ClassSchedule ClassSchedule { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
