//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerClub.DataAccess.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int IdType { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public byte[] Finger1 { get; set; }
        public byte[] Finger2 { get; set; }
        public string PhotoLink { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual TrainerType TrainerType { get; set; }
    }
}
