//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfGym.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfGym.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANIMO_CREAR_COTIZACIONES {
            get {
                object obj = ResourceManager.GetObject("ANIMO_CREAR_COTIZACIONES", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANIMO_DECLARACION {
            get {
                object obj = ResourceManager.GetObject("ANIMO_DECLARACION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANIMO_ICON_ACEPTAR_TARJETAS_DE_CREDITO {
            get {
                object obj = ResourceManager.GetObject("ANIMO_ICON_ACEPTAR_TARJETAS_DE_CREDITO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANIMO_ICON_AGREGAR_TARJETAS_DE_CREDITO {
            get {
                object obj = ResourceManager.GetObject("ANIMO_ICON_AGREGAR_TARJETAS_DE_CREDITO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANIMO_ICON_CONTACTOS_DE_EMERGENCIA {
            get {
                object obj = ResourceManager.GetObject("ANIMO_ICON_CONTACTOS_DE_EMERGENCIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANIMO_ICON_EDITARTRANSACCION_COMENTARIO_ON {
            get {
                object obj = ResourceManager.GetObject("ANIMO_ICON_EDITARTRANSACCION_COMENTARIO_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANIMO_ICON_ELIMINAR {
            get {
                object obj = ResourceManager.GetObject("ANIMO_ICON_ELIMINAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANIMO_ICON_MODIFICAR_TARJETAS_DE_CREDITO {
            get {
                object obj = ResourceManager.GetObject("ANIMO_ICON_MODIFICAR_TARJETAS_DE_CREDITO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ANIMO_ICON_SALIR {
            get {
                object obj = ResourceManager.GetObject("ANIMO_ICON_SALIR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HUELLA {
            get {
                object obj = ResourceManager.GetObject("HUELLA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_BANNER_LOGO {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_BANNER_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_BUSCARTICULOS_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_BUSCARTICULOS_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_DESCUENTOS_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_DESCUENTOS_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_EDITARTRANSACCIONES_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_EDITARTRANSACCIONES_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_EFECTIVO_OFF {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_EFECTIVO_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_ELIMINARTRANSACCION_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_ELIMINARTRANSACCION_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_MINIMIZARPANTALLA_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_MINIMIZARPANTALLA_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_MISCELANEOS_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_MISCELANEOS_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_PAGOS_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_PAGOS_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_REPORTEIMPFISCAL_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_REPORTEIMPFISCAL_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_SUSPENDER_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_SUSPENDER_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_TERMINAR_SESION_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_TERMINAR_SESION_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_TRANSACCION_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_TRANSACCION_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_ANIMO_HOME_TRANSACCIONCLIENTE_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_ANIMO_HOME_TRANSACCIONCLIENTE_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Buscar_Articulos_ON {
            get {
                object obj = ResourceManager.GetObject("Icon_Buscar_Articulos_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Buscar_Cliente_OFF1 {
            get {
                object obj = ResourceManager.GetObject("Icon_Buscar_Cliente_OFF1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_CALENDARIO {
            get {
                object obj = ResourceManager.GetObject("ICON_CALENDARIO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_CLASE {
            get {
                object obj = ResourceManager.GetObject("ICON_CLASE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_CLASE_OFF {
            get {
                object obj = ResourceManager.GetObject("ICON_CLASE_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_CLASE_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_CLASE_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Corte_X_ON {
            get {
                object obj = ResourceManager.GetObject("Icon_Corte_X_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_DISCIPLINA {
            get {
                object obj = ResourceManager.GetObject("ICON_DISCIPLINA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Eliminar_Item_ON {
            get {
                object obj = ResourceManager.GetObject("Icon_Eliminar_Item_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_AGREGARCLIENTE_GUARDARYSALIR {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_AGREGARCLIENTE_GUARDARYSALIR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_DEVOLVERTRANSACCION_CANTIDAD {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_DEVOLVERTRANSACCION_CANTIDAD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_DIALOGOS_ACEPTAR {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_DIALOGOS_ACEPTAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_DIALOGOS_CALENDARIO {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_DIALOGOS_CALENDARIO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_DIALOGOS_CONSULTATION {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_DIALOGOS_CONSULTATION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_DIALOGOS_ERROR {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_DIALOGOS_ERROR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_DIALOGOS_INFORMATION {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_DIALOGOS_INFORMATION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_DIALOGOS_NO {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_DIALOGOS_NO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_DIALOGOS_OK {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_DIALOGOS_OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_DIALOGOS_PLEASESETDATERANGE {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_DIALOGOS_PLEASESETDATERANGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_IDOPERADOR_APAGAR {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_IDOPERADOR_APAGAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_IDOPERADOR_CERRAR_OFF {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_IDOPERADOR_CERRAR_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_IDOPERADOR_CERRAR_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_IDOPERADOR_CERRAR_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GENERIC_IDOPERADOR_CONECTAR {
            get {
                object obj = ResourceManager.GetObject("ICON_GENERIC_IDOPERADOR_CONECTAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GREEN_HOME_AGREGARVENDEDOR_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_GREEN_HOME_AGREGARVENDEDOR_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_GREEN_HOME_INFORMACIONDELCLIENTE_OFF {
            get {
                object obj = ResourceManager.GetObject("ICON_GREEN_HOME_INFORMACIONDELCLIENTE_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon_Principal_Blanco_ON {
            get {
                object obj = ResourceManager.GetObject("Icon_Principal_Blanco_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_PWC_BANNER_LOGO {
            get {
                object obj = ResourceManager.GetObject("ICON_PWC_BANNER_LOGO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_PWC_HOME_TRAINING_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_PWC_HOME_TRAINING_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_REGISTRO_CLASE {
            get {
                object obj = ResourceManager.GetObject("ICON_REGISTRO_CLASE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_REGISTRO_CLASE_OFF {
            get {
                object obj = ResourceManager.GetObject("ICON_REGISTRO_CLASE_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_REGISTRO_CLASE_ON {
            get {
                object obj = ResourceManager.GetObject("ICON_REGISTRO_CLASE_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_REPORTE {
            get {
                object obj = ResourceManager.GetObject("ICON_REPORTE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_STAFF {
            get {
                object obj = ResourceManager.GetObject("ICON_STAFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_SUCURSAL {
            get {
                object obj = ResourceManager.GetObject("ICON_SUCURSAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICON_TRAINER {
            get {
                object obj = ResourceManager.GetObject("ICON_TRAINER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap POSLoginIDLogoOperador {
            get {
                object obj = ResourceManager.GetObject("POSLoginIDLogoOperador", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SILBATO {
            get {
                object obj = ResourceManager.GetObject("SILBATO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user2 {
            get {
                object obj = ResourceManager.GetObject("user2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap userIcon {
            get {
                object obj = ResourceManager.GetObject("userIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
